package(
    default_visibility = ["//visibility:public"],
)

java_library(
    name = "grpchealth",
    srcs = glob([
        "*.java",
    ]),
    deps = [
        "//vendor/github.com/binchencoder/third-party-java/dependencies/lib:grpc-1.18.0",
        "//vendor/github.com/binchencoder/third-party-java/dependencies/lib:slf4j-api-1.7.21",
    ],
)
